---
# DeployTracker\DashboardController routes
dashboard_index:
    path: /
    controller: DeployTracker\Controller\DashboardController::index

dashboard_recent:
    path: /recent
    controller: DeployTracker\Controller\DashboardController::recent

dashboard_history:
    path: /history
    controller: DeployTracker\Controller\DashboardController::history

dashboard_applications:
    path: /applications
    controller: DeployTracker\Controller\DashboardController::applications

dashboard_application:
    path: /application/{id}
    controller: DeployTracker\Controller\DashboardController::application
    requirements:
        id: \d+

# DeployTracker\SearchController routes
search_index:
    path: /search
    controller: DeployTracker\Controller\SearchController::index

# DeployTracker\ApiController routes
api_publish:
    path: /api/publish
    methods: [POST]
    controller: DeployTracker\Controller\ApiController::publish
    defaults: {_format: json}
